name: Build and Deploy
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: rreichel3/vuepress-github-actions-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: public/ # The folder, the action should deploy.
        BUILD_SCRIPT: npm install && npm run-script docs:build # The build script the action should run prior to deploying.
        GITHUB_ACTOR: ${GITHUB_ACTOR}
        PAGES_CNAME: rj3.me #Force rebuild
